#!/bin/bash
# Etersoft, 2010
# 2010 (c) Devaev Maxim, <mdevaev@etersoft.ru>
# 2010 (c) Baranov Denis, <baraka@etersoft.ru>
#
# rxsetup - script for fast configuration of NX
#
#####

unlock_nx_user()
{
        passwd -u nx
}

start_sshd()
{
        for sshd in ssh sshd openssh opensshd; do
                if [ -e /etc/init.d/$sshd ]; then
                        /etc/init.d/$sshd start
                        RETVAL="$?"
                        chkconfig $sshd on || update-rc.d $sshd defaults
                fi
        done

        return "$RETVAL"
}

enable_cupsd()
{
        chmod 755 /usr/sbin/cupsd && \
        chmod 711 /usr/lib/cups/backend/ipp
}

nx_install()
{
        nxsetup --setup-nomachine-key --install
}

start_freenx_server()
{
        chkconfig freenx-server on || update-rc.d freenx-server defaults
        /etc/init.d/freenx-server start
}

rxsetup_stages()
{
        unlock_nx_user &>rxsetup.log && \
        start_sshd >>rxsetup.log 2>&1 && \
        enable_cupsd >>rxsetup.log 2>&1 && \
        nx_install >>rxsetup.log 2>&1 && \
        start_freenx_server >>rxsetup.log 2>&1
        if [ "$?" -ne 0 ]; then
                echo "Configuration error, see rxsetup.log for details"
                exit 1
        else
                echo "Complete. Now, you may use nxclient for connection to this server"
        fi
}


##### Main #####
rxsetup_stages

