#!/bin/bash
# Etersoft, 2010
# 2010 (c) Devaev Maxim, <mdevaev@etersoft.ru>
# 2010 (c) Baranov Denis, <baraka@etersoft.ru>
#
# rxsetup - script for fast configuration of NX
#
#####

passwd -u nx

for sshd in ssh sshd openssh opensshd; do
	if [ -e /etc/init.d/$sshd ]; then
		/etc/init.d/$sshd start
		chkconfig $sshd on || update-rc.d $sshd defaults
	fi
done

#configure for printing
chmod 755 /usr/sbin/cupsd
chmod 711 /usr/lib/cups/backend/ipp

nxsetup --setup-nomachine-key --install

chkconfig freenx-server on || update-rc.d freenx-server defaults
/etc/init.d/freenx-server start

